services:
  - type: web
    name: hackerrank-scraper-api
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 1 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --timeout 300 --keep-alive 2 --max-requests 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        fromService:
          type: web
          name: hackerrank-scraper-api
          property: port
    scaling:
      minInstances: 1
      maxInstances: 3

