services:
  - type: web
    name: shastra-result
    runtime: docker
    repo: https://github.com/rohandol112/shastra_result
    dockerfilePath: ./Dockerfile
    numInstances: 1
    plan: starter
    healthCheckPath: /
    envVars:
      - key: DISPLAY
        value: ":99"
      - key: CHROME_BIN
        value: "/usr/bin/google-chrome"
      - key: CHROME_PATH
        value: "/usr/bin/google-chrome"